# -*- coding: utf-8 -*-
"""CTAI-026_ML_Lab_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q0BoNdvsnQxKFgWTGJxS2LQaFb8NYItT

**Linear Regression**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score

data = pd.read_csv("multiple_linear_regression_dataset_lab_01.csv")

data.head()

x = data.drop(['income'], axis=1)
y = data['income']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=2)

model = LinearRegression()

model.fit(x_train,y_train)

print("b=",model.coef_)
print("a =",model.intercept_)

pred = model.predict(x_test)
print(pred)

mse = mean_squared_error(y_test,pred)
mae = mean_absolute_error(y_test,pred)
rmse = np.sqrt(mean_squared_error(y_test,pred))
r2_score = r2_score(y_test,pred)

print(f"Mean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"Root Mean Squared Error: {rmse}")
print(f"r2_score: {r2_score}")

plt.scatter(y_test,pred)
plt.plot(y_test,y_test,'r')
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.show()

import joblib
joblib.dump(model,"CTAI-026_ML_Lab_01.pkl")

